### ISSUE TITLE
STS fails when property place holders are used

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/spring-ide#121]
(migrated from https://issuetracker.springsource.com/browse/STS-4303, please check for additional comments)

Basic issue is not able to resolve placeholders in eclipse like $
{FINOVERA_PROPERTIES} in following example. How do I tell to ignore PropertySources or pass my own property source? It creates severe functionality loss as it can not find almost every component/controller in the project. Works fine if the PropertySources annotation is commented out.

**Comment by MatWein** [comment]
Is there any plan to solve this issue in near future? I would like to use STS plugin for my daily work, but my company's projects mostly have such a placeholder in @PropertySource. Unfortunately it is impossible to use this plugin as long as this bug remains.

`org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [app.ApplicationMain]; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'webapp.home' in string value "file:${webapp.home}/server.properties"
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:187)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:321)
	at org.springframework.ide.eclipse.metadata.process.JdtConfigurationClassPostProcessor.postProcess(JdtConfigurationClassPostProcessor.java:88)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig$3.run(BeansJavaConfig.java:332)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig.executePostProcessor(BeansJavaConfig.java:321)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig.access$5(BeansJavaConfig.java:319)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig$2.call(BeansJavaConfig.java:233)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig$2.call(BeansJavaConfig.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'webapp.home' in string value "file:${webapp.home}/server.properties"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:204)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:178)
	at org.springframework.core.env.AbstractEnvironment.resolveRequiredPlaceholders(AbstractEnvironment.java:571)
	at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:385)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:260)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:237)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:204)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:173)
	... 14 more`

**Comment by martinlippert** [comment]
Not sure yet how to exactly solve this issue, deeply connected to the way the old Spring IDE creates the Spring model under the hood. But lets see what we can do here. Can you attach a sample project that reproduces this? Would help to investigate possible solutions a bit.

In addition to that if you remove the spring configuration from the project properties, this error should not happen anymore. I know that this workaround causes other features to not work properly anymore, but would be interested to learn which features you would loose that you would like to continue to use.

**Comment by MatWein** [comment]
Thanks for the quick reply. In the following attachment you will find a small example project to reproduce the problem:
[example.app.zip](https://github.com/spring-projects/spring-ide/files/1636315/example.app.zip)

I know its possible to avoid this problem by extracting the @PropertySource to its own @Configuration class and exclude it in settings. But unfortunately this is not always possible and I think it is a bad practice to change fully working production code, only to make the IDE working.

Most interesting features for me are:
- Detect dependency injection problems (Unsatisfied 'required' dependency of type ...)
- List request mappings
- Other validation mechanisms

**Comment by martinlippert** [comment]
Thanks for the sample project, thanks helps quite a bit. Since Spring IDE tries to create the bean model under the hood, the tooling tries to also use the `@PropertySource` annotation. The exception is being thrown because the placeholder in there `webapp.home` can't be resolved.

The question here is what the tooling should do in such a case. Ignoring the placeholder replacement doesn't work, since that doesn't help the property source annotation to run. Hmmm...

**Comment by martinlippert** [comment]
Okay, I found a relatively simple way to ignore missing property sources (e.g. due to the missing placeholder replacement) while building the beans model behind the scenes. This makes your sample project to build just fine without any errors and warnings showing up.

**Comment by MatWein** [comment]
Awesome! Thank you really much for your fast help. (interresting solution by the way :) )
