### ISSUE TITLE
Unable to find/resolve artifact with maven-dependency-plugin

### ISSUE THREAD

**Issue by marioja** [spring-projects/spring-ide#143]
When trying to create a pom file using the maven-dependency-plugin I get an error on the execution line in the pom file or in the Problem view in STS when trying to copy the just built artifact to a custom location as documented in the middle of this [maven documentation page](http://maven.apache.org/plugins/maven-dependency-plugin/examples/copying-artifacts.html).  The error I get is the following (I am trying to build this artifact: `net.mfjassociates.jai:jai-util:jar:1.2.12-SNAPSHOT`):
```
Unable to find/resolve artifact. (org.apache.maven.plugins:maven-dependency-plugin:3.0.0:copy:copy-installed:verify)

org.apache.maven.plugin.MojoExecutionException: Unable to find/resolve artifact.
	at org.apache.maven.plugins.dependency.fromConfiguration.AbstractFromConfigurationMojo.getArtifact(AbstractFromConfigurationMojo.java:253)
	at org.apache.maven.plugins.dependency.fromConfiguration.AbstractFromConfigurationMojo.getProcessedArtifactItems(AbstractFromConfigurationMojo.java:169)
	at org.apache.maven.plugins.dependency.fromConfiguration.CopyMojo.doExecute(CopyMojo.java:106)
	at org.apache.maven.plugins.dependency.AbstractDependencyMojo.execute(AbstractDependencyMojo.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at com.ianbrandt.tools.m2e.mdp.core.MdpBuildParticipant.executeMojo(MdpBuildParticipant.java:133)
	at com.ianbrandt.tools.m2e.mdp.core.MdpBuildParticipant.build(MdpBuildParticipant.java:67)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.maven.shared.artifact.resolve.ArtifactResolverException: Could not find artifact net.mfjassociates.jai:jai-util:jar:1.2.12-SNAPSHOT
	at org.apache.maven.shared.artifact.resolve.internal.Maven31ArtifactResolver.resolveArtifact(Maven31ArtifactResolver.java:116)
	at org.apache.maven.shared.artifact.resolve.internal.Maven31ArtifactResolver.resolveArtifact(Maven31ArtifactResolver.java:80)
	at org.apache.maven.shared.artifact.resolve.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:73)
	at org.apache.maven.plugins.dependency.fromConfiguration.AbstractFromConfigurationMojo.getArtifact(AbstractFromConfigurationMojo.java:249)
	... 37 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact net.mfjassociates.jai:jai-util:jar:1.2.12-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.apache.maven.shared.artifact.resolve.internal.Maven31ArtifactResolver.resolveArtifact(Maven31ArtifactResolver.java:108)
	... 40 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact net.mfjassociates.jai:jai-util:jar:1.2.12-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
	... 44 more
```
I strongly suspect that the issue is with the eclipse m2e plugin, not the maven-dependency-plugin as I am able to perform the copy operation when invoking maven itself.  The error is not always there.  It seems to always re-appear after a Maven/Update Project (alt-F5) menu command.
Please make sure you create the appropriate ticket with the m2e plugin group and do not just close this ticket (because the problem does not lie in the Spring STS code).  Please update this ticket with the m2e ticket number.

**Comment by marioja** [comment]
Actually, I found out where the m2e connector for the Maven Dependency Plugin is and created [issue 19](https://github.com/ianbrandt/m2e-maven-dependency-plugin/issues/19) for this problem.

**Comment by kdvolder** [comment]
Okay great! Thanks! I'll close this ticket now as the problem is m2e not STS.

**Comment by marioja** [comment]
Kris please do not close the ticket. STS uses the connector and STS is affected. Not only is it affected but you should be following up also on issue 19

**Comment by jhassony** [comment]
Any update on this issue? Any workaround? I tried using STS with existing working project (from latest eclipse) but this issue popped. I have this error on all my modules. This will probably make me dump STS

**Comment by martinlippert** [comment]
Can you attach (or point me to) a sample project that reproduces the issue (and maybe a few steps how to reproduce, starting from a fresh STS 3.9.0 install)? I would like to take an additional look to see what we can do about it.

**Comment by jhassony** [comment]
Sure. 
The attached workspace is the original one that works under a raw eclipse version (Version: Neon Release (4.6.0) Build id: 20160613-1800)

When reading it in STS, it has an error: 
**Unable to find artifact. (org.apache.maven.plugins:maven-dependency-plugin:2.8:copy:copy-generated-to-lib:install)**

STS first tells you the workspace was created in an older eclipse version, but after converting it it will show the compile error as described above.

Hope this helps to reproduce it.
Thanks

[workspace.zip](https://github.com/spring-projects/spring-ide/files/1141636/workspace.zip)

**Comment by martinlippert** [comment]
I tried your workspace, but there is no error showing up. Maybe because there are no dependencies defined and the build needs to copy...

In case this works just fine in plain Eclipse (so you don't need the maven-copy-dependencies integration for m2e), you could also try to uninstall that m2e connector (it gets installed as a root feature to allow easy uninstallation).

To do that, please go to the `About` dialog, select `Installation Details -> Installed Software`, select the `m2e connector for the Maven Dependency Plugin` and press `Uninstall...`.

**Comment by jhassony** [comment]
Thanks, but it didn't help. I still get the error. See attached pic.

Note that it doesn't matter that there is no source files or dependencies defined. in eclipse it complies successfully with no errors.

![2017-07-16 10_12_55-](https://user-images.githubusercontent.com/30105621/28245451-9e3bcf80-6a0f-11e7-897b-5a1a39e92394.png)

**Comment by martinlippert** [comment]
Maybe an issue with the local Maven repository and/or Maven wasn't able to get that Maven plugin somehow. Indeed strange. What happens if you run the context menu for that project and then `Maven -> Update Project...`, maybe selecting the "update snapshots/releases" and run. Does that help?

If that doesn't help, I would try to delete the local Maven repo (~/.m2/repository) and try again. That triggers Maven to download all the necessary components again (might take a while though). Or you can try to run Maven from the command line so see if that works.

Just a few ideas how to dive deeper to identify the issue here.

**Comment by Java-Point** [comment]
@marioja martinlippert-
It stops for some time and appears again immediately after the build completes.

**Comment by martinlippert** [comment]
I must admit that I am running out of ideas here and can't really reproduce the issue. Any change for a simple, self-contained sample project that would help me to reproduce this, starting from a fresh Spring Tools 4 for Eclipse distribution install? Or can someone confirm that this is indeed an issue with the m2e extension that we use? (https://github.com/ianbrandt/m2e-maven-dependency-plugin/issues/19)
