### ISSUE TITLE
STS freezes using Working Sets in Project Explorer view

### ISSUE THREAD

**Issue by AlessandroC85** [spring-projects/spring-ide#155]
Spring Tool Suite 

Version: 3.8.4.RELEASE
Build Id: 201703310825
Platform: Eclipse Neon.3 (4.6.3)

Operating System: macOS Sierra 10.12.2 (16C67)

Using the Working Sets in the "Project Explorer", STS hangs and freezes trying to expand the java resources folder of a Maven Project.

It happens with big projects, and I'm forced to close the IDE.

Disabling the Working sets, the issue disappears.

**Comment by martinlippert** [comment]
Can you capture a thread dump while STS/Eclipse hangs (using jps and jstack)? That would be great and could reveal more details about what is going on under the hood.

**Comment by AlessandroC85** [comment]
I've captured the thread dump while STS was freezed.
After some time (more than 2 minutes) it restored again himself.

Here the dump:

jstack -l 2114
2017-06-28 14:14:58
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode):

"Worker-51" #115 prio=5 os_prio=31 tid=0x000000012477d800 nid=0x16523 in Object.wait() [0x000070001485f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:188)
	- locked <0x0000000740e62820> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:52)

   Locked ownable synchronizers:
	- None

"Worker-50" #114 prio=5 os_prio=31 tid=0x0000000124195000 nid=0x13563 in Object.wait() [0x000070000c532000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:188)
	- locked <0x0000000740e62820> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:52)

   Locked ownable synchronizers:
	- None

"Attach Listener" #113 daemon prio=9 os_prio=31 tid=0x00000001223a6800 nid=0x1342b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Worker-49" #112 prio=5 os_prio=31 tid=0x0000000124f8a000 nid=0x12297 in Object.wait() [0x00007000102cd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:188)
	- locked <0x0000000740e62820> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:52)

   Locked ownable synchronizers:
	- None

"Worker-46" #109 prio=5 os_prio=31 tid=0x0000000100ceb800 nid=0xc80f in Object.wait() [0x0000700015ce8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:188)
	- locked <0x0000000740e62820> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:52)

   Locked ownable synchronizers:
	- None

"[ThreadPool Manager] - Idle Thread" #91 daemon prio=5 os_prio=31 tid=0x0000000105352800 nid=0x1440b in Object.wait() [0x000070002a7ce000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:106)
	- locked <0x000000074d0b1710> (a org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor)

   Locked ownable synchronizers:
	- None

"Thread-16" #79 prio=5 os_prio=31 tid=0x0000000129e8e000 nid=0x16f03 waiting on condition [0x0000700029dcb000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.objectaid.uml.license.LicenseManager.createSocket(LicenseManager.java:180)
	at com.objectaid.uml.license.LicenseManager$1.run(LicenseManager.java:121)

   Locked ownable synchronizers:
	- None

"Timer-2" #78 prio=5 os_prio=31 tid=0x00000001249bd800 nid=0x16107 in Object.wait() [0x00007000289c5000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000074909f9a0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

   Locked ownable synchronizers:
	- None

"SVN Kit 1.8 Connector" #77 prio=5 os_prio=31 tid=0x000000012453e000 nid=0x16c07 in Object.wait() [0x0000700027fc2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.polarion.team.svn.connector.svnkit.SVNKitService$ProgressMonitorThread.run(SVNKitService.java:201)
	- locked <0x0000000748727870> (a java.util.ArrayList)

   Locked ownable synchronizers:
	- None

"Timer-1" #76 daemon prio=5 os_prio=31 tid=0x000000012a33b800 nid=0x16b0b in Object.wait() [0x000070002623c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000074871c768> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

   Locked ownable synchronizers:
	- None

"Provisioning Event Dispatcher" #73 daemon prio=5 os_prio=31 tid=0x000000012a20b000 nid=0x16903 in Object.wait() [0x00007000293c8000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	- locked <0x00000007488c5bd0> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

   Locked ownable synchronizers:
	- None

"Timer-0" #70 prio=5 os_prio=31 tid=0x000000012212d000 nid=0x16303 in Object.wait() [0x00007000275bf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000074878b868> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

   Locked ownable synchronizers:
	- None

"org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor" #36 daemon prio=1 os_prio=31 tid=0x0000000124994000 nid=0x10c07 in Object.wait() [0x0000700013459000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:667)
	- locked <0x00000007444c4f60> (a java.util.Collections$SynchronizedRandomAccessList)

   Locked ownable synchronizers:
	- None

"org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor" #34 daemon prio=1 os_prio=31 tid=0x0000000105069000 nid=0x10613 in Object.wait() [0x0000700012a56000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:667)
	- locked <0x000000074456d0d0> (a java.util.Collections$SynchronizedRandomAccessList)

   Locked ownable synchronizers:
	- None

"JavaScript indexing" #33 daemon prio=4 os_prio=31 tid=0x00000001242d6000 nid=0x10a0b in Object.wait() [0x0000700012053000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.wst.jsdt.internal.core.search.processing.JobManager.run(JobManager.java:370)
	- locked <0x00000007447de7c0> (a org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"EventAdmin Async Event Dispatcher Thread" #30 daemon prio=6 os_prio=31 tid=0x0000000102b69800 nid=0xe50f in Object.wait() [0x000070001154a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	- locked <0x00000007437392a0> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

   Locked ownable synchronizers:
	- None

"Java indexing" #26 daemon prio=4 os_prio=31 tid=0x00000001208c6800 nid=0xd413 in Object.wait() [0x000070000f741000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:371)
	- locked <0x0000000742c32150> (a org.eclipse.jdt.internal.core.search.indexing.IndexManager)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Thread-2" #19 daemon prio=1 os_prio=31 tid=0x00000001052ed000 nid=0xd203 waiting on condition [0x000070000ed3e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000740c53530> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at org.eclipse.equinox.weaving.internal.caching.CacheWriter$1.run(CacheWriter.java:47)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"EMF Reference Cleaner" #18 daemon prio=5 os_prio=31 tid=0x0000000100d9a000 nid=0xd003 in Object.wait() [0x000070000e33b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000007411c39b0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)

   Locked ownable synchronizers:
	- None

"Worker-JM" #17 prio=5 os_prio=31 tid=0x0000000105467000 nid=0xce0b in Object.wait() [0x000070000d938000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.InternalWorker.run(InternalWorker.java:59)
	- locked <0x0000000740e62b30> (a java.util.ArrayList)

   Locked ownable synchronizers:
	- None

"[Timer] - Main Queue Handler" #16 daemon prio=5 os_prio=31 tid=0x0000000100b59800 nid=0xca03 in Object.wait() [0x000070000cf35000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.equinox.internal.util.impl.tpt.timer.TimerImpl.run(TimerImpl.java:141)
	- locked <0x00000007411c3d38> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Start Level: Equinox Container: 3cd71cda-c689-4d2d-83bc-b846b9c9ca46" #14 daemon prio=5 os_prio=31 tid=0x0000000102a23000 nid=0xb503 in Object.wait() [0x000070000bb2f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	- locked <0x0000000740bf0a90> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

   Locked ownable synchronizers:
	- None

"Framework Event Dispatcher: org.eclipse.osgi.internal.framework.EquinoxEventPublisher@23468512" #13 daemon prio=5 os_prio=31 tid=0x0000000100b6c800 nid=0xb303 in Object.wait() [0x000070000b12c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	- locked <0x00000007411e3a60> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

   Locked ownable synchronizers:
	- None

"Bundle File Closer" #12 daemon prio=5 os_prio=31 tid=0x000000010178f000 nid=0xb103 in Object.wait() [0x000070000a729000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	- locked <0x00000007411e3fd0> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

   Locked ownable synchronizers:
	- None

"Active Thread: Equinox Container: 3cd71cda-c689-4d2d-83bc-b846b9c9ca46" #10 prio=5 os_prio=31 tid=0x00000001013cc000 nid=0xae13 waiting on condition [0x0000700009d26000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007411e4688> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x0000000100891000 nid=0x6e03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x0000000100886000 nid=0x6c03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x000000010087b800 nid=0x6a03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x000000010087a000 nid=0x6803 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x000000010103c800 nid=0x6603 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x0000000101037000 nid=0x6103 in Object.wait() [0x0000700007b11000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000007407d6a48> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x000000010102d800 nid=0x5f03 in Object.wait() [0x000070000710e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000007407d6a88> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
	- None

"main" #1 prio=6 os_prio=31 tid=0x000000010082c000 nid=0x307 runnable [0x00007fff5fbf9000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at java.util.Collections$SynchronizedMap.get(Collections.java:2584)
	- locked <0x000000074324d960> (a java.util.Collections$SynchronizedMap)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.getFolder(ExternalFoldersManager.java:324)
	at org.eclipse.jdt.internal.core.JavaProject.contains(JavaProject.java:761)
	at org.eclipse.jdt.internal.core.JavaModel.contains(JavaModel.java:94)
	at org.eclipse.jdt.internal.ui.JavaElementContainmentAdapter.contains(JavaElementContainmentAdapter.java:43)
	at org.eclipse.ui.ResourceWorkingSetFilter.isEnclosed(ResourceWorkingSetFilter.java:97)
	at org.eclipse.ui.ResourceWorkingSetFilter.select(ResourceWorkingSetFilter.java:63)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:56)
	at org.eclipse.ui.ResourceWorkingSetFilter.filter(ResourceWorkingSetFilter.java:159)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.hasFilteredChildren(NonEssentialElementsFilter.java:79)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.select(NonEssentialElementsFilter.java:65)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:56)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.hasFilteredChildren(NonEssentialElementsFilter.java:79)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.select(NonEssentialElementsFilter.java:65)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:56)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.hasFilteredChildren(NonEssentialElementsFilter.java:79)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.select(NonEssentialElementsFilter.java:65)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:56)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.hasFilteredChildren(NonEssentialElementsFilter.java:79)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.select(NonEssentialElementsFilter.java:65)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:56)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.hasFilteredChildren(NonEssentialElementsFilter.java:79)
	at org.eclipse.jdt.internal.ui.navigator.NonEssentialElementsFilter.select(NonEssentialElementsFilter.java:65)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:56)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:911)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:621)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$0(AbstractTreeViewer.java:815)
	at org.eclipse.jface.viewers.AbstractTreeViewer$$Lambda$49/1135738295.run(Unknown Source)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:795)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:596)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:766)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1493)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:882)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.treeExpanded(AbstractTreeViewer.java:1505)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:133)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.TreeItem.sendExpand(TreeItem.java:1050)
	at org.eclipse.swt.widgets.Tree.expandItem_expandChildren(Tree.java:1278)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5996)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:227)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1135)
	at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2102)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1127)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2624)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2069)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5733)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:227)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2140)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2402)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5797)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5226)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5375)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3703)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 tid=0x0000000105012000 nid=0x5d03 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x000000010083c000 nid=0x5503 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x000000010083d000 nid=0x5703 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x000000010083d800 nid=0x5903 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x000000010083e000 nid=0x5b03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x000000010103e000 nid=0x7003 waiting on condition 

JNI global references: 4314

With jps no informations:

jps -l 2114
RMI Registry not available at 2114:1099
Exception creating connection to: 2114; nested exception is: 
	java.net.NoRouteToHostException: No route to host (Host unreachable)

**Comment by martinlippert** [comment]
Looks like this is related to external files and/or folders being included in your workspace and that the implementation around that is something slow. Since this seems to be closely related to the underlying Eclipse platform and probably the JDT implementation, I would recommend to open a bug via https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT for them to have a look (and attach the thread dump).

**Comment by AlessandroC85** [comment]
Thanks for the explanation.
In case of JDT will find a solution, it would be integrated in next releases of STS ?

**Comment by martinlippert** [comment]
In general, yes, we always ship on top of the latest Eclipse release. Eclipse Oxygen (4.7) ships today (and STS 3.9.0 on top of that probably next week). So the next maintenance release for this would be Eclipse Oxygen.1, scheduled for September (and I am sure that we will have an STS update shortly after that includes Oxygen.1).

The biggest question is which Eclipse release will get that fix... :-)
If you want that to be included in Oxygen.1 (for September), you should ask it to be included in there, otherwise it might ship as part of Eclipse Photon in June 2018...

**Comment by AlessandroC85** [comment]
Ok, so I will report to JDT, hoping that they will found a solution!
Thanks again.
