### ISSUE TITLE
3.9.0 AWS S3 Access Not Working

### ISSUE THREAD

**Issue by tautera** [spring-projects/spring-ide#166]
3.8.4. AWS Put object works successfully.  Running same in 3.9.0 fails on the following.  All is the same between 3.8.4 and 3.9.0.

```2017-07-13 17:27:54.278 ERROR 12132 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: C699DB8CBAF89036), S3 Extended Request ID: b9ZCwZluB7+9EklEklphh/jsfVHcfWgUz2JZWPjvrIFE0mvKiTymtk+cSvRTGKwmOsqYBFdT/Oc=] with root cause

com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: C699DB8CBAF89036)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305) ~[aws-java-sdk-core-1.11.1.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852) ~[aws-java-sdk-core-1.11.1.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630) ~[aws-java-sdk-core-1.11.1.jar:na]
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405) ~[aws-java-sdk-core-1.11.1.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367) ~[aws-java-sdk-core-1.11.1.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318) ~[aws-java-sdk-core-1.11.1.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3785) ~[aws-java-sdk-s3-1.11.1.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1399) ~[aws-java-sdk-s3-1.11.1.jar:na]
	at com.cannalysis.services.AwsServiceImpl.uploadInputStreamToAws(AwsServiceImpl.java:62) ~[classes/:na]
	at com.cannalysis.services.AwsServiceImpl.uploadFileToAwsS3(AwsServiceImpl.java:36) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.sun.proxy.$Proxy169.uploadFileToAwsS3(Unknown Source) ~[na:na] ```

**Comment by martinlippert** [comment]
Looks like this happens inside of a Spring app that you are running, not within the IDE itself, right? Strange that is worked when running from STS 3.8.4 but not from STS 3.9.0. Are you sure you are running it with the same JDK and the same config/location?

**Comment by kdvolder** [comment]
How are the S3 keys injected to your running app? If via vm or commandline arguments... this bug could be interfering with that process: #159

**Comment by tautera** [comment]
Environment is the exactly the same.  I have upgraded before with no issues.  Same exact source, pom, etc.  Key's are injected thru vm -D args.  Good point let me try something else there.

**Comment by tautera** [comment]
Okay, I got my app / aws S3 access to work by providing the AWS keys thru java and basic authentication (just as a test :).  But, ran into another issue.  In my normal vm args have have 3 -D args.  
-Dspring.profiles.active=dev,devMysql -Daws.accessKeyId=xxxxx -Daws.secrectKey=yyyyy.  When I removed the 2 -D aws args, The app failed to come up, as it did not see spring.profiles.active var.  I put a dummy -D arg after the profile arg, and the app came up (and works)!:
-Dspring.profiles.active=dev,devMysql -Dabc.dummy=dev

**Comment by tautera** [comment]
Ahhh ... my prev comment , gave me an idea that worked.  It seems the IDE does not see the last vm arg!  When I provided my normal 3 args as described above, AND the dummy arg as described above, all works.

**Comment by kdvolder** [comment]
> Environment is the exactly the same. I have upgraded before with no issues

Yes, but the bug I linked is a new bug that came with 3.9.0 (unfortunately).

From the sound of your workarounds, I'd say this is indeed another manifestation of that particular bug. So closing this as a 'duplicate' of #159 

Be sure to speak up though, if you disagree with that assessment.

**Comment by martinlippert** [comment]
(please note that is this is a result of #159 the simple workaround for this is to disable the fast startup option in the preferences)
