### ISSUE TITLE
Can't connect to any repository: session is down

### ISSUE THREAD

**Issue by mhayen** [spring-projects/spring-ide#210]
Since the latest update my Eclipse with the Spring tools won't push and/or pull to/from remote repositories, while my commandline git operations still are working.

These are the error message is the Error log:
An exception occurred during push on URI ssh://git@bitbucket.org/xxxx/xxxx.git: ssh://git@bitbucket.org/xxxx/xxxx.git: session is down
org.eclipse.jgit.api.errors.TransportException: ssh://git@bitbucket.org/xxxx/xxxx.git: session is down
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:180)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:215)
	at org.eclipse.egit.ui.internal.push.PushJob.performJob(PushJob.java:84)
	at org.eclipse.egit.ui.internal.jobs.RepositoryJob.run(RepositoryJob.java:57)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://git@bitbucket.org/xxxx/xxxx.git: session is down
	at org.eclipse.jgit.transport.JschSession$JschProcess.<init>(JschSession.java:160)
	at org.eclipse.jgit.transport.JschSession.exec(JschSession.java:92)
	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:332)
	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:174)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:160)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1310)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:169)
	... 4 more
Caused by: com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:762)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at org.eclipse.jgit.transport.JschSession$JschProcess.<init>(JschSession.java:152)
	... 10 more

Session Data:

eclipse.buildId=4.7.1.M20171009-0410
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  Lombok -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 Lombok -product org.eclipse.epp.package.jee.product

**Comment by martinlippert** [comment]
This seems to be an issue with the Git integration for Eclipse (EGit), therefore I would recommend to report this bug to: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit

**Comment by mhayen** [comment]
Well, I've been using Eclipse with EGit and Spring tools happily together for a while now.
Never had any trouble, until I installed the latest Spring Tools update.

**Comment by martinlippert** [comment]
Hmmm... Understand... That is strange. Did the update maybe also change the version of EGit? Sometimes you get a whole bunch of updates at once... :-)

I think we should try to find the root cause here. Can you try to install the latest EGit tooling into a plain Eclipse Oxygen.1a-JEE to see if that works? And maybe a fresh STS 3.9.1 distro install to see if that works?

Sorry for asking for all that, just trying to find out what is causing this...

**Comment by mhayen** [comment]
I understand no problem.
Downloaded a fresh Eclipse Oxygen.1a-JEE and push to remote git succeeds.
Added Spring tools 3.9.1, still ok.
run update, found updates for Git integration for Eclipse	4.9.0.201710071750-r
After installing this Git update, the push stops working.
So it looks like the EGit update causes the troubles.

**Comment by bjornoss** [comment]
Hi, I can confirm that I also has this problem after last update. 
Let me know if you want me to provide more information.

**Comment by dfons** [comment]
I'm having the same issue. I've already reported a bug. In my case the problem started after the last EGit update. I'm using Eclipse with CDT only.

**Comment by Dayologic** [comment]
Any updates on the resolution of this issue?  It's still occurring with the latest Eclipse and Egit versions.

**Comment by martinlippert** [comment]
Did anybody report this issue to the EGit project (as suggested above)?
