### ISSUE TITLE
 java.lang.NoSuchMethodError: org.springframework.tooling.ls.eclipse.commons.STS4LanguageServerProcessStreamConnector: method <init>()V not found

### ISSUE THREAD

**Issue by ahoehma** [spring-projects/spring-ide#253]
-- Error Details --
Date: Fri Mar 16 11:46:16 CET 2018
Message: Plug-in "org.springframework.tooling.boot.java.ls" was unable to instantiate class "org.springframework.tooling.boot.java.ls.DelegatingStreamConnectionProvider".
Severity: Error
Product: Spring Tool Suite 4 4.0.0.201802231815-M9 (org.springframework.boot.ide.branding.sts4)
Plugin: org.eclipse.lsp4e
Session Data:
eclipse.buildId=4.0.0.201712141343-M7
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.springframework.boot.ide.branding.sts4
Command-line arguments:  -data file:/D:/Dev/ws-goos-development/ -os win32 -ws win32 -arch x86_64 -clean -product org.springframework.boot.ide.branding.sts4

Exception Stack Trace:
org.eclipse.core.runtime.CoreException: Plug-in "org.springframework.tooling.boot.java.ls" was unable to instantiate class "org.springframework.tooling.boot.java.ls.DelegatingStreamConnectionProvider".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:188)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:107)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:171)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:460)
	at org.eclipse.lsp4e.LanguageServerWrapper.getServer(LanguageServerWrapper.java:444)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:357)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NoSuchMethodError: org.springframework.tooling.ls.eclipse.commons.STS4LanguageServerProcessStreamConnector: method <init>()V not found
	at org.springframework.tooling.boot.java.ls.SpringBootJavaLanguageServer.<init>(SpringBootJavaLanguageServer.java:34)
	at org.springframework.tooling.boot.java.ls.DelegatingStreamConnectionProvider.<init>(DelegatingStreamConnectionProvider.java:63)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	... 10 more

-- Error Details --
Date: Fri Mar 16 11:46:16 CET 2018
Message: Plug-in "org.springframework.tooling.boot.java.ls" was unable to instantiate class "org.springframework.tooling.boot.java.ls.DelegatingStreamConnectionProvider".
Severity: Error
Product: Spring Tool Suite 4 4.0.0.201802231815-M9 (org.springframework.boot.ide.branding.sts4)
Plugin: org.eclipse.equinox.registry
Exception Stack Trace:
java.lang.NoSuchMethodError: org.springframework.tooling.ls.eclipse.commons.STS4LanguageServerProcessStreamConnector: method <init>()V not found
	at org.springframework.tooling.boot.java.ls.SpringBootJavaLanguageServer.<init>(SpringBootJavaLanguageServer.java:34)
	at org.springframework.tooling.boot.java.ls.DelegatingStreamConnectionProvider.<init>(DelegatingStreamConnectionProvider.java:63)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:107)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:171)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:460)
	at org.eclipse.lsp4e.LanguageServerWrapper.getServer(LanguageServerWrapper.java:444)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:357)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by martinlippert** [comment]
Looks like this is an older STS4 milestone build that got updated to a newer version (M9). As mentioned here: https://github.com/spring-projects/sts4/wiki/Changelog#2018-02-23 we refactored the structure of the language server for Spring Boot, therefore updating an M8 or M7 install would require a few manual steps to get things going again - or you start with a fresh M9 (or M10 if you wait another day or two). I would recommend to start with a fresh M10.
