### ISSUE TITLE
java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira

### ISSUE THREAD

**Issue by objectboy2016** [spring-projects/spring-ide#258]
java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:110)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
	at java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass(InvokerBytecodeGenerator.java:284)
	at java.lang.invoke.InvokerBytecodeGenerator.loadMethod(InvokerBytecodeGenerator.java:276)
	at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:618)
	at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:654)
	at java.lang.invoke.Invokers.callSiteForm(Invokers.java:381)
	at java.lang.invoke.Invokers.linkToTargetMethod(Invokers.java:347)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:314)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at java.util.stream.Collectors.groupingBy(Collectors.java:906)
	at java.util.stream.Collectors.groupingBy(Collectors.java:853)
	at java.util.stream.Collectors.groupingBy(Collectors.java:805)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findExecutableMetaData(AnnotationMetaDataProvider.java:304)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getMetaData(AnnotationMetaDataProvider.java:285)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getMethodMetaData(AnnotationMetaDataProvider.java:272)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:134)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.<init>(AnnotationMetaDataProvider.java:109)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.<init>(BeanMetaDataManager.java:145)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.lambda$createValidator$0(ValidatorFactoryImpl.java:340)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.createValidator(ValidatorFactoryImpl.java:331)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.getValidator(ValidatorFactoryImpl.java:233)
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$ValidationInitializer.run(BackgroundPreinitializer.java:142)
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.runSafely(BackgroundPreinitializer.java:92)
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.run(BackgroundPreinitializer.java:82)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.tryToEnsureSystemClassesInitialized(SpringLoadedPreProcessor.java:373)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:135)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
	... 28 more

**Operating environment:   jdk 8, spring boot 2 ,   idea**

**However, this problem does not affect the normal operation of the project.**

**Comment by martinlippert** [comment]
It looks like SpringLoaded is part of the game here. I am not sure about the status of that project and whether this is still under active development, so you might want to take a look at Spring Boot Devtools instead. Did you? It doesn't provide the same level of hot-swap changed code, but helps you with quickly restarting your boot app in case you change your code. Maybe that works for you, too?

If not and you would like to continue with SpringLoaded, I would suggest to report this here: https://github.com/spring-projects/spring-loaded. There is probably a related issue already filed, so you might want to take a look and add a comment, if you find one.
