### ISSUE TITLE
NPE in RestartAction

### ISSUE THREAD

**Issue by madisparn** [spring-projects/spring-ide#278]
Using: org.springsource.sts_3.9.4.201804120921-RELEASE
```
!ENTRY org.eclipse.ui.console 4 120 2018-05-04 10:02:36.016
!MESSAGE Error logged from Console plug-in: 
!STACK 0
java.lang.NullPointerException
	at org.springframework.ide.eclipse.boot.restart.RestartAction.update(RestartAction.java:56)
	at org.springframework.ide.eclipse.boot.restart.RestartAction.<init>(RestartAction.java:44)
	at org.springframework.ide.eclipse.boot.restart.RestartConsolePageParticipant.init(RestartConsolePageParticipant.java:58)
	at org.springframework.ide.eclipse.boot.restart.RestartConsolePageParticipant.init(RestartConsolePageParticipant.java:54)
	at org.eclipse.ui.internal.console.ConsoleView$3.run(ConsoleView.java:326)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.console.ConsoleView.doCreatePage(ConsoleView.java:323)
	at org.eclipse.ui.part.PageBookView.createPage(PageBookView.java:385)
	at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:728)
	at org.eclipse.ui.internal.console.ConsoleView$4.run(ConsoleView.java:395)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4577)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4186)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by kdvolder** [comment]
Do you have anything more to add to  this bug report? A little bit of context info would be useful. For example, is this just some error you found logged in the error log? Or does it actually cause something to malfunction to the point it doesn't work for you? Are there any specific sequence of steps that cause the problem reliably? If the answer is yes, it would be very helpful to include those steps.

**Comment by madisparn** [comment]
JRebel plugin is running integration tests against different eclipse versions using eclipse rcptt platform.
For some reason the JRebel console is not showing up in STS sometimes and this error was visible in the logs. But I was not able to reproduce the problem manually.

**Comment by kdvolder** [comment]
I am not exactly sure why launch configuration might be null sometimes. But it seems like a null check is in order, so I added one.
