### ISSUE TITLE
[Spring Tool Suit 3.9.4] devtools not work Failed to read Class-Path arrtibute from mainifest of logback-classic-1.2.3.jar

### ISSUE THREAD

**Issue by purple-dragon** [spring-projects/spring-ide#301]
pom.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.scorpio</groupId>
	<artifactId>SpringStart-1</artifactId>
	<version>0.0.1</version>
	<packaging>jar</packaging>

	<name>SpringStart-1</name>
	<description>Spring Boot Start Project</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.3.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

error when start it

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalStateException: Failed to read Class-Path attribute from manifest of jar file:/Users/<username>/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:132)
	at org.springframework.boot.devtools.restart.ChangeableUrls.fromClassLoader(ChangeableUrls.java:98)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:91)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:55)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:142)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:556)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartingEvent(RestartApplicationListener.java:67)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.scorpio.SpringStartApplication.main(SpringStartApplication.java:13)
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.IOUtils.readFully(IOUtils.java:65)
	at java.util.jar.JarFile.getBytes(JarFile.java:425)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromManifestClassPathAttribute(ChangeableUrls.java:153)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:129)
	... 17 more

**Comment by purple-dragon** [comment]
I checked
.m2/repository/ch/qos/logback/logback-classic/1.2.3/

something still in-progress

-rw-r--r--  1 user  staff   13081  6  3 20:08 logback-classic-1.2.3.pom
-rw-r--r--  1 user  staff      40  6  3 20:08 logback-classic-1.2.3.pom.sha1
**-rw-r--r--  1 user  staff      40  6  3 20:09 aether-f12ae9f5-1b4d-4e7b-bdc5-55f2ddaa128d-logback-classic-1.2.3.jar.sha1-in-progress**
-rw-r--r--  1 user  staff  481177  6  3 20:09 logback-classic-1.2.3.jar
-rw-r--r--  1 user  staff     568  6  3 20:11 logback-classic-1.2.3.jar.lastUpdated
-rw-r--r--  1 user  staff  230201  6  3 20:11 logback-classic-1.2.3-sources.jar
-rw-r--r--  1 user  staff      40  6  3 20:11 logback-classic-1.2.3-sources.jar.sha1
-rw-r--r--  1 user  staff     246  6  3 20:11 _remote.repositories
-rw-r--r--  1 user  staff      98  6  3 20:12 m2e-lastUpdated.properties

**Comment by purple-dragon** [comment]
fixed by manually download the jars

**Comment by kdvolder** [comment]
Sounds ike it was a issue with the maven repository rather than a malfunction of STS or devtools. So I'm closing this issue. Feel free to re-open and add further comments if you think this is somehow STS or devtools fault.

**Comment by purple-dragon** [comment]
hi @kdvolder  
not sure if it's the issue of maven repository or STS.
anyway, how can i re-download jars from maven repository? not manually
Thank you

**Comment by martinlippert** [comment]
You can do a right click on the project, then do a `Maven -> Update Project...` and select the `Force Download Releases/Snapshots`. This should re-download the JARs (in theory). My experience is that it is better to wipe the local maven repo altogether and trigger the `Update Project` afterwards to let maven download the necessary dependencies.

**Comment by purple-dragon** [comment]
@martinlippert  thank you for the reply.

below command can help re-download jars
1. find ~/.m2/repository/ -name "*progress*"   
2. find ~/.m2/repository/ -name "*progress*" | xargs rm -f  // cleanup dirty files
3. mvn clean compile       // will download compile time jar
4. mvn spring-boot:run    // will download runtime jar
5. right click project & Maven -> Update Project...
