### ISSUE TITLE
STS hangs and uses 100% CPU when console is open with ANSI console enabled and dark theme

### ISSUE THREAD

**Issue by athnix** [spring-projects/spring-ide#306]
When using the dark theme in STS and having console open, the IDE starts to hang and becomes unresponsive, and uses up the entire CPU core. This happens regardless if any app is running, as long as there is enough text in the console. 

Switching away from the console tab, closing or clearing the console makes the IDE work normally, but as soon as there is more than ~10 lines in the console it becomes unresponsive again.

Disabling the ANSI console resolves the hang problem, but the console output becomes ugly and hard to read with plenty of mojibake wherever there's supposed to be a color change.

The issue seems to be between the dark theme and ANSI console, perhaps they are clashing by each trying to set the console's color in a loop? However, the issue is [reported here](https://github.com/mihnita/ansi-econsole/issues/27) and the developer of ansi-econsole suggests that it may be an issue with STS because he can't reproduce it in vanilla Eclipse with either theme.

Version info:
Spring Tool Suite 3.9.5.201807031753-RELEASE-e48 org.springsource.sts.ide
Ansi Console 1.3.3.201605090119 net.mihai-nita.ansicon.feature.group

**Comment by martinlippert** [comment]
I tried an STS 3.9.5 release build and I am not running into this problem... :-( However, I am on macOS, so that might behave differently here, since your original report tells me you are on Windows, right? Would be good to know if updating the JDK helps here.

Can you also take a few thread dumps while STS hangs or is unresponsive (using jps and jstack) and attach them here? That might help to reveal what is going wrong here.

**Comment by athnix** [comment]
Yes, I'm on Windows 10. JDK version is 1.8.0_181.

Here's the result of jstack while the IDE hangs when I try to scroll through the console:

```
C:\Users\Andrija>jstack 10324
2018-08-20 14:51:23
Full thread dump Java HotSpot(TM) Client VM (25.181-b13 mixed mode):

"RMI RenewClean-[localhost:56967]" #627 daemon prio=5 os_prio=0 tid=0x392e0800 nid=0x26bc in Object.wait() [0x4fdaf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x0fc27770> (a java.lang.ref.ReferenceQueue$Lock)
        at sun.rmi.transport.DGCClient$EndpointEntry$RenewCleanThread.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"AWT-Windows" #623 daemon prio=6 os_prio=0 tid=0x392e4000 nid=0x5f64 runnable [0x4feaf000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WToolkit.eventLoop(Native Method)
        at sun.awt.windows.WToolkit.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Java2D Disposer" #621 daemon prio=10 os_prio=2 tid=0x3c43b400 nid=0x5e90 in Object.wait() [0x4fb6f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x0fc27b28> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at sun.java2d.Disposer.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Worker-91" #620 prio=5 os_prio=0 tid=0x3c43b000 nid=0x5488 in Object.wait() [0x4fa6f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:197)
        - locked <0x1920bb40> (a org.eclipse.core.internal.jobs.WorkerPool)
        at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:239)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

"Worker-87" #550 prio=5 os_prio=0 tid=0x389bc400 nid=0x7270 in Object.wait() [0x4f86f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:197)
        - locked <0x1920bb40> (a org.eclipse.core.internal.jobs.WorkerPool)
        at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:239)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

"org.eclipse.jdt.internal.ui.text.JavaReconciler" #502 daemon prio=1 os_prio=-2 tid=0x3c43e800 nid=0x210c in Object.wait() [0x4f96f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:180)
        - locked <0x1ff30ef0> (a org.eclipse.jface.text.reconciler.DirtyRegionQueue)

"RMI RenewClean-[localhost:56517]" #396 daemon prio=5 os_prio=0 tid=0x392dfc00 nid=0x3d6c in Object.wait() [0x4d50f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x1eec1730> (a java.lang.ref.ReferenceQueue$Lock)
        at sun.rmi.transport.DGCClient$EndpointEntry$RenewCleanThread.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Worker-42: File Transport Cancel Handler" #278 prio=5 os_prio=0 tid=0x3c437c00 nid=0x6500 waiting on condition [0x47bff000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.eclipse.equinox.internal.p2.transport.ecf.FileReader$CancelHandler.run(FileReader.java:154)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

"Worker-41: File Transport Cancel Handler" #277 prio=5 os_prio=0 tid=0x3c43d400 nid=0x3cfc waiting on condition [0x46a6f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.eclipse.equinox.internal.p2.transport.ecf.FileReader$CancelHandler.run(FileReader.java:154)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

"Worker-40: File Transport Cancel Handler" #275 prio=5 os_prio=0 tid=0x3c43ec00 nid=0x3ba4 waiting on condition [0x4109f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.eclipse.equinox.internal.p2.transport.ecf.FileReader$CancelHandler.run(FileReader.java:154)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

"Worker-35: File Transport Cancel Handler" #237 prio=5 os_prio=0 tid=0x389b7400 nid=0x2d98 waiting on condition [0x50fcf000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.eclipse.equinox.internal.p2.transport.ecf.FileReader$CancelHandler.run(FileReader.java:154)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

"Recommenders-Timeout-Manager" #225 prio=5 os_prio=0 tid=0x389ba000 nid=0x3dd0 waiting on condition [0x528cf000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x1e849f38> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Timer-0" #220 daemon prio=6 os_prio=0 tid=0x389b8400 nid=0x1e8 in Object.wait() [0x5234f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.util.TimerThread.mainLoop(Unknown Source)
        - locked <0x1e84a150> (a java.util.TaskQueue)
        at java.util.TimerThread.run(Unknown Source)

"com.google.inject.internal.util.$Finalizer" #218 daemon prio=6 os_prio=0 tid=0x392df000 nid=0x5bcc in Object.wait() [0x51e4f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x1e84a318> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at com.google.inject.internal.util.$Finalizer.run(Finalizer.java:114)

"RMI Scheduler(0)" #93 daemon prio=5 os_prio=0 tid=0x3c439400 nid=0x89c4 waiting on condition [0x3e79f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x1e1dd0b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Thread-9" #49 prio=5 os_prio=0 tid=0x392e0000 nid=0x847c waiting on condition [0x47acf000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:87)

"EventAdmin Async Event Dispatcher Thread" #33 daemon prio=6 os_prio=0 tid=0x389bc000 nid=0xef8 in Object.wait() [0x45f6f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked <0x1c4b1228> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

"JavaScript indexing" #30 daemon prio=4 os_prio=-1 tid=0x389ba400 nid=0x7904 in Object.wait() [0x419df000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.wst.jsdt.internal.core.search.processing.JobManager.run(JobManager.java:370)
        - locked <0x1ba1ac58> (a org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager)
        at java.lang.Thread.run(Unknown Source)

"Java indexing" #26 daemon prio=4 os_prio=-1 tid=0x389b9800 nid=0x46f4 in Object.wait() [0x3d85f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:375)
        - locked <0x1a3d3d70> (a org.eclipse.jdt.internal.core.search.indexing.IndexManager)
        at java.lang.Thread.run(Unknown Source)

"Gogo shell" #23 prio=5 os_prio=0 tid=0x389bd800 nid=0x4770 waiting on condition [0x3b45f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x19df1810> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
        at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Thread-2" #20 daemon prio=1 os_prio=-2 tid=0x389b6c00 nid=0x79e0 waiting on condition [0x3b1df000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x19dce5d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
        at java.util.concurrent.ArrayBlockingQueue.take(Unknown Source)
        at org.eclipse.equinox.weaving.internal.caching.CacheWriter$1.run(CacheWriter.java:47)
        at java.lang.Thread.run(Unknown Source)

"Provisioning Event Dispatcher" #19 daemon prio=5 os_prio=0 tid=0x38729c00 nid=0x4950 in Object.wait() [0x3af9f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked <0x19b35938> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

"EMF Reference Cleaner" #17 daemon prio=5 os_prio=0 tid=0x38729400 nid=0x4224 in Object.wait() [0x3aa1f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x1912e0b8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)

"Worker-JM" #16 prio=5 os_prio=0 tid=0x38729000 nid=0x3c28 in Object.wait() [0x3a8df000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.eclipse.core.internal.jobs.InternalWorker.run(InternalWorker.java:59)
        - locked <0x1912e258> (a java.util.ArrayList)

"SCR Component Actor" #15 daemon prio=5 os_prio=0 tid=0x3872ac00 nid=0x6620 in Object.wait() [0x39baf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x1828b528> (a java.util.LinkedList)
        at java.lang.Object.wait(Unknown Source)
        at org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:81)
        - locked <0x1828b528> (a java.util.LinkedList)
        at java.lang.Thread.run(Unknown Source)

"Refresh Thread: Equinox Container: c8650e7f-e0c6-4d3c-a291-3ba28348f403" #14 daemon prio=5 os_prio=0 tid=0x3872a800 nid=0x4d70 in Object.wait() [0x39a6f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x1821ef08> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked <0x1821ef08> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

"Framework Event Dispatcher: Equinox Container: c8650e7f-e0c6-4d3c-a291-3ba28348f403" #13 daemon prio=5 os_prio=0 tid=0x38728000 nid=0x14a0 in Object.wait() [0x3982f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked <0x1821f090> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

"Start Level: Equinox Container: c8650e7f-e0c6-4d3c-a291-3ba28348f403" #12 daemon prio=5 os_prio=0 tid=0x38728800 nid=0x7adc in Object.wait() [0x396ef000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked <0x1821f218> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

"Bundle File Closer" #11 daemon prio=5 os_prio=0 tid=0x3872bc00 nid=0x4750 in Object.wait() [0x395af000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked <0x17d24c18> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)

"Active Thread: Equinox Container: c8650e7f-e0c6-4d3c-a291-3ba28348f403" #9 prio=5 os_prio=0 tid=0x3872a000 nid=0x4a08 waiting on condition [0x38c6f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x17c850c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x3792c800 nid=0x242c runnable [0x00000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x37924000 nid=0x3f8 waiting on condition [0x00000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x3792fc00 nid=0x2570 waiting on condition [0x00000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x3792dc00 nid=0x3cb0 runnable [0x00000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x3791a400 nid=0x418c in Object.wait() [0x37cff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x1722cf50> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x37904400 nid=0x4e10 in Object.wait() [0x37bff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at java.lang.ref.Reference.tryHandlePending(Unknown Source)
        - locked <0x1722d0f0> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" #1 prio=6 os_prio=0 tid=0x050fcc00 nid=0x90c runnable [0x00b3d000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.swt.internal.win32.OS.ScriptShape(Native Method)
        at org.eclipse.swt.graphics.TextLayout.shape(TextLayout.java:3378)
        at org.eclipse.swt.graphics.TextLayout.shape(TextLayout.java:3558)
        at org.eclipse.swt.graphics.TextLayout.computeRuns(TextLayout.java:247)
        at org.eclipse.swt.graphics.TextLayout.getBounds(TextLayout.java:1631)
        at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:290)
        at org.eclipse.swt.custom.StyledTextRenderer.calculateClientArea(StyledTextRenderer.java:318)
        at org.eclipse.swt.custom.StyledText.resetCache(StyledText.java:8026)
        at org.eclipse.swt.custom.StyledText.redraw(StyledText.java:7571)
        at org.eclipse.e4.ui.internal.css.swt.dom.scrollbar.StyledTextThemedScrollBarAdapter$StyledTextPaintListener.redrawScrollBars(StyledTextThemedScrollBarAdapter.java:662)
        at org.eclipse.e4.ui.internal.css.swt.dom.scrollbar.AbstractThemedScrollBarAdapter.checkChangedHorizontalAndTopPixel(AbstractThemedScrollBarAdapter.java:421)
        at org.eclipse.e4.ui.internal.css.swt.dom.scrollbar.AbstractThemedScrollBarAdapter.widgetSelected(AbstractThemedScrollBarAdapter.java:536)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
        at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1093)
        at org.eclipse.swt.widgets.ScrollBar.wmScrollChild(ScrollBar.java:999)
        at org.eclipse.swt.widgets.Scrollable.wmScroll(Scrollable.java:479)
        at org.eclipse.swt.widgets.Scrollable.WM_VSCROLL(Scrollable.java:370)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:4852)
        at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:345)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:4765)
        at org.eclipse.swt.internal.win32.OS.SendMessageW(Native Method)
        at org.eclipse.swt.internal.win32.OS.SendMessage(OS.java:2943)
        at org.eclipse.swt.widgets.Scrollable.wmScrollWheel(Scrollable.java:400)
        at org.eclipse.swt.widgets.Scrollable.WM_MOUSEWHEEL(Scrollable.java:353)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:4813)
        at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:345)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:4757)
        at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
        at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2303)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3532)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
        at org.eclipse.ui.internal.Workbench$$Lambda$28/27120336.run(Unknown Source)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1498)

"VM Thread" os_prio=2 tid=0x04ffd000 nid=0x89e8 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x3795b000 nid=0x7f28 waiting on condition

JNI global references: 1898


```

**Comment by martinlippert** [comment]
From looking at the thread dump (thanks for that), it looks like the Spring-specific tooling it not involved here, but it is running swat-related platform code here. Hard to say what the underlying problem really is. Is this problem still there on your machine and happens every time you do this? Even when using the latest STS 3.9.6 release on Eclipse 2018-09? If so, I think we should also report this to the Eclipse SWT platform project, would be good to hear from them what they think. But can you double check using the latest version again?

**Comment by kunlan** [comment]
I have a similar problem, when I use the dark theme, clicking on the console panel will not respond. Classic themes and light themes not.

**Comment by martinlippert** [comment]
@kunlan can you provide a few more details? Operating system/version, STS version, and JDK version would be useful, also a thread dump while STS hangs, if possible, could reveal more details.

**Comment by martinlippert** [comment]
Another option here would be to uninstall the ANSI coloring plugin. That way you would loose the coloring in the console output though.

But if you disable the console coloring when starting the Spring app, you won't get the ANSI color codes in the console output.

**Comment by zack10** [comment]
I am using  STS version 4.4.2.RELEASE and still getting the same problem when I use dark theme, every time the console is launched STS starts freezing, but when I switch to light theme the problem disappears, is this bug still unsolved I noticed it's been open since Aug 2018?

**Comment by kdvolder** [comment]
@zack10  I just tried to run a boot app in STS 4.4.2 using Dark theme and experienced no problems. I am on Linux though. Could be this issue is specific to Windows only.

Let me try if it works fine in my Windows VM.

**Comment by zack10** [comment]
@kdvolder maybe it's specific to windows. I'm using Windows 10 and every time I tried to run my project on dark them STS crushes and stops responding

**Comment by kdvolder** [comment]
First I thought it was working fine for me in Windows VM as well. But then after playing around a bit the STS window become unresponsive. I'm trying now if disabling ansi console helps at all.

**Comment by kdvolder** [comment]
After disabling the ansi console from preference (i.e go to "Window >> Preferences >> Ansi Console" then uncheck the 'enabled' box). The problem appears to be resolved. So I think this is a problem with the Ansi Console somehow. 

So I think the problem should be raised here:

https://github.com/mihnita/ansi-econsole/issues

**Comment by zack10** [comment]
Yes that's the problem I did the same thing and disabled Ansi Console and the problem stopped occurring, but the console, on the other hand, looks a bit weird the colors really help differentiating between error, warning and info logs especially with long console logs.
thanks @kdvolder hope this bug gets solved soon.

**Comment by kdvolder** [comment]
@zack10 I don't think its our bug to fix as this seems to be a problem with the Ansi Console plugin. 

We really should have alerted it's maintainer/owner of the problem when it was first discovered in 2018. I have done that now here:

https://github.com/mihnita/ansi-econsole/issues/43

**Comment by kdvolder** [comment]
> but the console, on the other hand, looks a bit weird the colors really help differentiating between error, warning and info logs especially with long console logs

Yes, the ansi console is a nice feature, we like it too, which why we include it in our distribution :-). Unfortunately for the time being I really don't have better advice than either:

- use the light theme instead.
- disable the ansi console.

**Comment by zack10** [comment]
Yes exactly. I switched to light theme, and it works great,  thanks @kdvolder I hope the maintainers of Ansi Console plugin will fix the bug in the next update :)

**Comment by athnix** [comment]
> @zack10  We really should have alerted it's maintainer/owner of the problem when it was first discovered in 2018. I have done that now here: [mihnita/ansi-econsole#43](https://github.com/mihnita/ansi-econsole/issues/43)

There's actually a bug report from 2017 for this issue: https://github.com/mihnita/ansi-econsole/issues/27

I've linked to it in my OP, but there was no confirmation if it actually has to do with ansi-econsole or STS. Since then, the ansi-econsole maintainer has managed to identify the cause somewhat, but doesn't have a solution yet.
