### ISSUE TITLE
Exception (nullpointer) while running spring boot maven project via boot dashboard

### ISSUE THREAD

**Issue by dhruv-bansal** [spring-projects/spring-ide#324]
I am getting the following exception when I am trying to run spring boot maven project from boot dashboard

```
!ENTRY Activator 4 0 2018-09-24 16:46:55.345
!MESSAGE NullPointerException: null
!STACK 0
java.lang.NullPointerException
    at org.eclipse.m2e.jdt.internal.MavenClassifierManager.getClassifierClasspathProvider(MavenClassifierManager.java:131)
    at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.addProjectEntries(MavenRuntimeClasspathProvider.java:275)
    at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.addMavenClasspathEntries(MavenRuntimeClasspathProvider.java:183)
    at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.resolveClasspath0(MavenRuntimeClasspathProvider.java:148)
    at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider$1.call(MavenRuntimeClasspathProvider.java:133)
    at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider$1.call(MavenRuntimeClasspathProvider.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
    at org.eclipse.m2e.jdt.internal.launch.MavenRuntimeClasspathProvider.resolveClasspath(MavenRuntimeClasspathProvider.java:130)
    at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.resolveClasspath(RuntimeClasspathProvider.java:65)
    at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1719)
    at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspathAndModulepath(AbstractJavaLaunchConfigurationDelegate.java:459)
    at org.springframework.ide.eclipse.boot.launch.BootLaunchConfigurationDelegate.getClasspathAndModulepath(BootLaunchConfigurationDelegate.java:566)
    at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:77)
    at org.springframework.ide.eclipse.boot.launch.AbstractBootLaunchConfigurationDelegate.launch(AbstractBootLaunchConfigurationDelegate.java:333)
    at org.springframework.ide.eclipse.boot.launch.BootLaunchConfigurationDelegate.launch(BootLaunchConfigurationDelegate.java:151)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:859)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by kdvolder** [comment]
I am not getting that exception. So perhaps something specific about the project triggers that problem. Any chance you could share a sample project. Either the project you are getting this problem with that itself, or some cut-down version that still triggers the problem?

Without a way to reproduce this there is really very little that we can do.

**Comment by kdvolder** [comment]
BTW: It is also possible its not a problem with the project but something in the workspace / project state. So you could try things like doing a project 'clean' build from project menu, or 'Maven update' of the project from 'Maven' context menu. If you try this, let us know if it makes a difference.

**Comment by martinlippert** [comment]
This might be related to this issue in m2e:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479245

Do you always get the error, even after restarting the IDE? And do you get error independent of the project that you are trying to start or does it happen for a specific project only?
