### ISSUE TITLE
STS freezes when running springboot application

### ISSUE THREAD

**Issue by minimanu** [spring-projects/spring-ide#344]
DUMP WITH JSTACK

```
2019-02-11 16:50:32
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode):

"JMX client heartbeat 9" #1447 daemon prio=5 os_prio=0 tid=0x0000000027b70800 nid=0xe0c waiting on condition [0x000000004bfee000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"RMI RenewClean-[localhost:61727]" #1446 daemon prio=5 os_prio=0 tid=0x0000000027b69000 nid=0x349c in Object.wait() [0x000000004beee000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	- locked <0x00000000dcd81aa0> (a java.lang.ref.ReferenceQueue$Lock)
	at sun.rmi.transport.DGCClient$EndpointEntry$RenewCleanThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Process monitor" #1445 daemon prio=5 os_prio=0 tid=0x0000000027b6d000 nid=0x5268 runnable [0x000000004bdef000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ProcessImpl.waitForInterruptibly(Native Method)
	at java.lang.ProcessImpl.waitFor(Unknown Source)
	at org.eclipse.debug.core.model.RuntimeProcess$ProcessMonitorThread.run(RuntimeProcess.java:427)

"Input Stream Monitor" #1444 daemon prio=5 os_prio=0 tid=0x0000000027b6b800 nid=0xd3c in Object.wait() [0x000000004bcef000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.debug.internal.core.InputStreamMonitor.writeNext(InputStreamMonitor.java:154)
	- locked <0x00000000dcc03d30> (a java.lang.Object)
	at org.eclipse.debug.internal.core.InputStreamMonitor.write(InputStreamMonitor.java:123)
	at org.eclipse.debug.internal.core.InputStreamMonitor.lambda$0(InputStreamMonitor.java:100)
	at org.eclipse.debug.internal.core.InputStreamMonitor$$Lambda$747/296055372.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Output Stream Monitor" #1443 daemon prio=1 os_prio=-2 tid=0x0000000027b70000 nid=0x5254 runnable [0x000000004bbef000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	- locked <0x00000000dcd83ec0> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.eclipse.debug.internal.core.OutputStreamMonitor.read(OutputStreamMonitor.java:150)
	at org.eclipse.debug.internal.core.OutputStreamMonitor.lambda$0(OutputStreamMonitor.java:212)
	at org.eclipse.debug.internal.core.OutputStreamMonitor$$Lambda$746/742835226.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Output Stream Monitor" #1442 daemon prio=1 os_prio=-2 tid=0x0000000027b6a800 nid=0x35a8 runnable [0x000000004baef000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	- locked <0x00000000dcc03c50> (a java.io.BufferedInputStream)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	- locked <0x00000000dcc03c78> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.eclipse.debug.internal.core.OutputStreamMonitor.read(OutputStreamMonitor.java:150)
	at org.eclipse.debug.internal.core.OutputStreamMonitor.lambda$0(OutputStreamMonitor.java:212)
	at org.eclipse.debug.internal.core.OutputStreamMonitor$$Lambda$746/742835226.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"org.eclipse.jdt.internal.ui.text.JavaReconciler" #967 daemon prio=1 os_prio=-2 tid=0x000000001e876000 nid=0x26ec in Object.wait() [0x0000000066afe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:183)
	- locked <0x00000000ca180238> (a org.eclipse.jface.text.reconciler.DirtyRegionQueue)

"RMI TCP Connection(idle)" #927 daemon prio=5 os_prio=0 tid=0x0000000033c25000 nid=0x1ee0 waiting on condition [0x00000000640fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c0780048> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"GC Daemon" #628 daemon prio=2 os_prio=-2 tid=0x0000000033c1f000 nid=0x3a88 in Object.wait() [0x00000000501df000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at sun.misc.GC$Daemon.run(Unknown Source)
	- locked <0x00000000c6605cf8> (a sun.misc.GC$LatencyLock)

"RMI RenewClean-[localhost:54000]" #627 daemon prio=5 os_prio=0 tid=0x0000000033c18000 nid=0x4174 in Object.wait() [0x00000000500de000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	- locked <0x00000000c6605e80> (a java.lang.ref.ReferenceQueue$Lock)
	at sun.rmi.transport.DGCClient$EndpointEntry$RenewCleanThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Worker-21" #619 prio=5 os_prio=0 tid=0x000000001d9b0800 nid=0x3990 in Object.wait() [0x000000004f8df000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	- locked <0x00000000c63aa288> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-20" #618 prio=5 os_prio=0 tid=0x000000001d9b2800 nid=0x13b4 in Object.wait() [0x000000004f7de000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	- locked <0x00000000c63aa288> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"org.eclipse.jdt.internal.ui.text.JavaReconciler" #429 daemon prio=1 os_prio=-2 tid=0x0000000027b65000 nid=0x5350 in Object.wait() [0x000000005771f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:183)
	- locked <0x00000000c6682888> (a org.eclipse.jface.text.reconciler.DirtyRegionQueue)

"JMX server connection timeout 77" #77 daemon prio=5 os_prio=0 tid=0x0000000027b76000 nid=0x22b4 in Object.wait() [0x000000004054f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at com.sun.jmx.remote.internal.ServerCommunicatorAdmin$Timeout.run(Unknown Source)
	- locked <0x00000000c6885cd8> (a [I)
	at java.lang.Thread.run(Unknown Source)

"RMI Scheduler(0)" #76 daemon prio=5 os_prio=0 tid=0x0000000027b76800 nid=0x2f58 waiting on condition [0x000000004044e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c6885e70> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"RMI TCP Accept-0" #69 daemon prio=5 os_prio=0 tid=0x0000000027b67800 nid=0x18bc runnable [0x000000003ec7f000]
   java.lang.Thread.State: RUNNABLE
	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
	at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
	at java.net.PlainSocketImpl.accept(Unknown Source)
	- locked <0x00000000c6886300> (a java.net.SocksSocketImpl)
	at java.net.ServerSocket.implAccept(Unknown Source)
	at java.net.ServerSocket.accept(Unknown Source)
	at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"pool-2-thread-1" #55 prio=5 os_prio=0 tid=0x000000001d9a9800 nid=0x4a18 runnable [0x0000000039a3e000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	- locked <0x00000000c2d86b10> (a java.io.BufferedInputStream)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Thread-8" #52 prio=5 os_prio=0 tid=0x0000000033cf9800 nid=0x2478 waiting on condition [0x00000000393bf000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:73)

"Worker-12: Consume LS error stream" #49 prio=5 os_prio=0 tid=0x0000000033cf2000 nid=0x350c runnable [0x000000003853f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.springsource.ide.eclipse.commons.core.util.IOUtil.consume(IOUtil.java:26)
	at org.springframework.tooling.ls.eclipse.commons.STS4LanguageServerProcessStreamConnector$1.run(STS4LanguageServerProcessStreamConnector.java:57)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

"Worker-9" #46 prio=5 os_prio=0 tid=0x0000000033cf7000 nid=0x17c4 in Object.wait() [0x000000003823f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	- locked <0x00000000c63aa288> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-8" #45 prio=5 os_prio=0 tid=0x0000000033cf4000 nid=0xaac in Object.wait() [0x000000003813f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	- locked <0x00000000c63aa288> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-7" #44 prio=5 os_prio=0 tid=0x0000000033cf5000 nid=0x3d2c in Object.wait() [0x000000003803f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	- locked <0x00000000c63aa288> (a org.eclipse.core.internal.jobs.WorkerPool)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

"Worker-4: Process Console Input Job" #41 prio=5 os_prio=0 tid=0x0000000033cf6800 nid=0x4c78 in Object.wait() [0x0000000037d3f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.ui.console.IOConsoleInputStream.waitForData(IOConsoleInputStream.java:154)
	at org.eclipse.ui.console.IOConsoleInputStream.read(IOConsoleInputStream.java:97)
	- locked <0x00000000dcc03d00> (a org.eclipse.ui.console.IOConsoleInputStream)
	at org.eclipse.ui.console.IOConsoleInputStream.read(IOConsoleInputStream.java:123)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole$InputReadJob.run(ProcessConsole.java:737)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

"EventAdmin Async Event Dispatcher Thread" #38 daemon prio=6 os_prio=0 tid=0x000000001d356000 nid=0x5318 in Object.wait() [0x0000000037a3f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	- locked <0x00000000c1b06b30> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"org.eclipse.jdt.internal.ui.text.JavaReconciler" #36 daemon prio=1 os_prio=-2 tid=0x000000001d359800 nid=0x3150 in Object.wait() [0x0000000035c4f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:183)
	- locked <0x00000000c4b34188> (a org.eclipse.jface.text.reconciler.DirtyRegionQueue)

"Java indexing" #34 daemon prio=4 os_prio=-1 tid=0x000000001d356800 nid=0x2e34 in Object.wait() [0x000000002706e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:378)
	- locked <0x00000000c4394fd8> (a org.eclipse.jdt.internal.core.search.indexing.IndexManager)
	at java.lang.Thread.run(Unknown Source)

"EMF Reference Cleaner" #32 daemon prio=6 os_prio=0 tid=0x000000001d7c0000 nid=0x1eec in Object.wait() [0x000000002557e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	- locked <0x00000000c0333be8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)

"Gogo shell" #28 prio=5 os_prio=0 tid=0x000000001d7c5800 nid=0x3494 waiting on condition [0x000000002111f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c0394b28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Provisioning Event Dispatcher" #24 daemon prio=5 os_prio=0 tid=0x000000001d7c1800 nid=0x1be0 in Object.wait() [0x0000000020c1f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	- locked <0x00000000c6331c20> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Worker-JM" #22 prio=5 os_prio=0 tid=0x000000001a9e6800 nid=0x4cf0 in Object.wait() [0x000000001f9bf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.InternalWorker.run(InternalWorker.java:62)
	- locked <0x00000000c63aa5b8> (a java.util.ArrayList)

"SCR Component Actor" #21 daemon prio=5 os_prio=0 tid=0x000000001e20b000 nid=0x1fec in Object.wait() [0x000000001f6bf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:81)
	- locked <0x00000000c5683a50> (a java.util.LinkedList)
	at java.lang.Thread.run(Unknown Source)

"Bundle File Closer" #19 daemon prio=5 os_prio=0 tid=0x000000001bc4b000 nid=0x418 in Object.wait() [0x000000001cfbf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	- locked <0x00000000c0f81540> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Refresh Thread: Equinox Container: 9afc1624-ce65-4d68-a506-43263b9160ed" #18 daemon prio=5 os_prio=0 tid=0x000000001a7e1000 nid=0x4a38 in Object.wait() [0x000000001ccbf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	- locked <0x00000000c1000000> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Start Level: Equinox Container: 9afc1624-ce65-4d68-a506-43263b9160ed" #17 daemon prio=5 os_prio=0 tid=0x000000001a644800 nid=0x447c in Object.wait() [0x000000001cbbe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	- locked <0x00000000c0f816c8> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Framework Event Dispatcher: Equinox Container: 9afc1624-ce65-4d68-a506-43263b9160ed" #16 daemon prio=5 os_prio=0 tid=0x000000001a643800 nid=0x1f10 in Object.wait() [0x000000001cabe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:403)
	- locked <0x00000000c0f01280> (a org.eclipse.osgi.framework.eventmgr.EventManager$EventThread)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

"Active Thread: Equinox Container: 9afc1624-ce65-4d68-a506-43263b9160ed" #14 prio=5 os_prio=0 tid=0x000000001a691000 nid=0x2dd4 waiting on condition [0x000000001c9be000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c0f819c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"Service Thread" #10 daemon prio=9 os_prio=0 tid=0x00000000193f4000 nid=0x3b9c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #9 daemon prio=9 os_prio=2 tid=0x000000001936a800 nid=0x5170 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #8 daemon prio=9 os_prio=2 tid=0x0000000019366000 nid=0x38a0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 tid=0x0000000019318800 nid=0x78 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #6 daemon prio=5 os_prio=2 tid=0x0000000019317800 nid=0xb98 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #5 daemon prio=9 os_prio=2 tid=0x0000000019312800 nid=0xd14 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x0000000019361800 nid=0x202c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000000192fa000 nid=0x53fc in Object.wait() [0x00000000198af000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	- locked <0x00000000c00f0dc8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000192f3000 nid=0x20c4 in Object.wait() [0x00000000197af000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	- locked <0x00000000c00f0db8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" #1 prio=6 os_prio=0 tid=0x0000000003200800 nid=0x5088 runnable [0x00000000012fe000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.win32.OS.WaitMessage(Native Method)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:4547)
	at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopIdle(WorkbenchAdvisor.java:371)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.eventLoopIdle(IDEWorkbenchAdvisor.java:961)
	at org.eclipse.ui.internal.Workbench$1.eventLoopIdle(Workbench.java:482)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1178)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.ui.internal.Workbench$$Lambda$66/254513404.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

"VM Thread" os_prio=2 tid=0x000000001868e000 nid=0x46b4 runnable 

"Gang worker#0 (Parallel GC Threads)" os_prio=2 tid=0x0000000003218800 nid=0x2bcc runnable 

"Gang worker#1 (Parallel GC Threads)" os_prio=2 tid=0x000000000321b000 nid=0x4460 runnable 

"Gang worker#2 (Parallel GC Threads)" os_prio=2 tid=0x000000000321d000 nid=0x46e4 runnable 

"Gang worker#3 (Parallel GC Threads)" os_prio=2 tid=0x000000000321f800 nid=0x413c runnable 

"G1 Main Concurrent Mark GC Thread" os_prio=2 tid=0x0000000003279800 nid=0x4d9c runnable 

"Gang worker#0 (G1 Parallel Marking Threads)" os_prio=2 tid=0x000000000327a800 nid=0x50dc runnable 

"G1 Concurrent Refinement Thread#0" os_prio=2 tid=0x0000000003228000 nid=0x31d8 runnable 

"G1 Concurrent Refinement Thread#1" os_prio=2 tid=0x0000000003227000 nid=0x32b4 runnable 

"G1 Concurrent Refinement Thread#2" os_prio=2 tid=0x0000000003225800 nid=0x23e0 runnable 

"G1 Concurrent Refinement Thread#3" os_prio=2 tid=0x0000000003222800 nid=0xe7c runnable 

"G1 Concurrent Refinement Thread#4" os_prio=2 tid=0x0000000003221000 nid=0x2ba8 runnable 

"String Deduplication Thread" os_prio=2 tid=0x000000001861c000 nid=0x4568 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x00000000193fb800 nid=0x4420 waiting on condition 

JNI global references: 2266
```

**Comment by martinlippert** [comment]
Unfortunately the thread dump doesn't reveal any hints why STS freeze. Can you provide a few steps how to reproduce the freeze? And which version of STS you run? And maybe a sample project that you run and causes the IDE to freeze?

**Comment by minimanu** [comment]
So
It just stopped freezing without a reason
I don't know why
Thank you Martin

**Comment by martinlippert** [comment]
Ok, good to hear that. In case you come across the freezes again, please comment and we can re-open this issue.
