### ISSUE TITLE
Unable launch project: NPE

### ISSUE THREAD

**Issue by 452** [spring-projects/spring-ide#411]
https://youtu.be/5YxHK5yQGjA
Spring Tool Suite 4 
Version: 4.5.1.RELEASE
Build Id: 202001211336

```
!ENTRY org.eclipse.core.jobs 4 2 2020-03-11 18:10:45.373
!MESSAGE An internal error occurred during: "Launching Operational".
!STACK 0
java.lang.NullPointerException
	at org.springframework.ide.eclipse.boot.launch.AbstractBootLaunchConfigurationDelegate.configureClassPathProviders(AbstractBootLaunchConfigurationDelegate.java:377)
	at org.springframework.ide.eclipse.boot.launch.AbstractBootLaunchConfigurationDelegate.launch(AbstractBootLaunchConfigurationDelegate.java:359)
	at org.springframework.ide.eclipse.boot.launch.BootLaunchConfigurationDelegate.launch(BootLaunchConfigurationDelegate.java:155)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1017)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by 452** [comment]
https://github.com/spring-projects/sts4/issues/418
